# Generated by Django 5.1.3 on 2025-04-05 13:12

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_folder_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
